name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  test:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: 8.x
          cache: true
          cache-dependency-path: Waratah/*/packages.lock.json

      - name: Restore
        run: dotnet restore Waratah\Waratah.sln --locked-mode

      - name: Test
        run: dotnet test Waratah\Waratah.sln

  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [x64, arm64]
        os: [win, osx, linux]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: 8.x
          cache: true
          cache-dependency-path: Waratah/*/packages.lock.json

      - name: Restore
        run: dotnet restore Waratah/Waratah.sln --locked-mode

      - name: Build
        run: dotnet build Waratah/Waratah.sln -c Release

      - name: Publish
        run: dotnet publish Waratah/WaratahCmd/WaratahCmd.csproj -c Release -r ${{ matrix.os }}-${{ matrix.arch }} -p:SelfContained=true

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4.0.0
        with:
          name: waratah-${{ matrix.os }}-${{ matrix.arch }}.zip
          path: Waratah/WaratahCmd/bin/Release/net8.0/${{ matrix.os }}-${{ matrix.arch }}/publish/
